---
- name: Inventory Management Block
  block:
    - name: Add the Hosts in Inventory
      add_host:
        hostname: '{{item}}'
        groups: servers
      loop: "{{ Hostname.split(',') | list}}"
      register: inmemory_inventory
  
